//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 10.0
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !NO_EXPORT_APP_MAIN
  public HDevelopExport()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("do_low_error", "false");
    action();
  }
#endif

  // Main procedure 
  private void action()
  {

    // Local control variables 

    HTuple hv_A, hv_b, hv_B=new HTuple();

    // Initialize local and output iconic variables 

    hv_A = 1;
    hv_b = 2;
    if ((int)(new HTuple(hv_A.TupleGreater(hv_B))) != 0)
    {
      hv_A = hv_A+1;
    }

  }


}
#if !NO_EXPORT_APP_MAIN
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

